# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ChannelBrowser.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChannelBrowser(object):
    def setupUi(self, ChannelBrowser):
        ChannelBrowser.setObjectName("ChannelBrowser")
        ChannelBrowser.resize(430, 385)
        self.centralwidget = QtWidgets.QWidget(ChannelBrowser)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.MplPlotArea = HistViewer(self.frame)
        self.MplPlotArea.setObjectName("MplPlotArea")
        self.verticalLayout_2.addWidget(self.MplPlotArea)
        self.statesGridWidget = StatesGrid(self.frame)
        self.statesGridWidget.setObjectName("statesGridWidget")
        self.verticalLayout_2.addWidget(self.statesGridWidget)
        self.csWindow = QtWidgets.QGroupBox(self.frame)
        self.csWindow.setMaximumSize(QtCore.QSize(16777215, 50))
        self.csWindow.setObjectName("csWindow")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.csWindow)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.csWindow)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.frame_2 = QtWidgets.QFrame(self.csWindow)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkBox = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_2.addWidget(self.checkBox)
        self.channelBox = QtWidgets.QSpinBox(self.frame_2)
        self.channelBox.setMinimum(1)
        self.channelBox.setMaximum(99999)
        self.channelBox.setObjectName("channelBox")
        self.horizontalLayout_2.addWidget(self.channelBox)
        self.horizontalLayout.addWidget(self.frame_2)
        self.viewPlotButton = QtWidgets.QPushButton(self.csWindow)
        self.viewPlotButton.setObjectName("viewPlotButton")
        self.horizontalLayout.addWidget(self.viewPlotButton)
        self.verticalLayout_2.addWidget(self.csWindow)
        self.selectedChannelButton = QtWidgets.QPushButton(self.frame)
        self.selectedChannelButton.setObjectName("selectedChannelButton")
        self.verticalLayout_2.addWidget(self.selectedChannelButton)
        self.verticalLayout.addWidget(self.frame)
        ChannelBrowser.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(ChannelBrowser)
        self.statusbar.setObjectName("statusbar")
        ChannelBrowser.setStatusBar(self.statusbar)

        self.retranslateUi(ChannelBrowser)
        QtCore.QMetaObject.connectSlotsByName(ChannelBrowser)

    def retranslateUi(self, ChannelBrowser):
        _translate = QtCore.QCoreApplication.translate
        ChannelBrowser.setWindowTitle(_translate("ChannelBrowser", "MainWindow"))
        self.csWindow.setTitle(_translate("ChannelBrowser", "Select Channel(s)"))
        self.label.setText(_translate("ChannelBrowser", "Channel:"))
        self.checkBox.setText(_translate("ChannelBrowser", "All Channels"))
        self.viewPlotButton.setText(_translate("ChannelBrowser", "View Plot"))
        self.selectedChannelButton.setText(_translate("ChannelBrowser", "Use this channel as the reference channel"))
from massGui.massless import HistViewer, StatesGrid
